# ServiceNow STAGING environment config
# Run with: mvn test -Denv=staging
# Credentials injected via environment variables (see ConfigurationManager)

service.now.base.uri=https://staging.service-now.com
service.now.base.path=/api/now/table/
service.now.oauth.base.path=/oauth_token.do
service.now.grant.type=password
service.now.client.id=bdf6e206861c41118c5be851d34499aa
service.now.client.secret=?9:^*N7$#m
